name: examples


on:
  release:
    types: [published]


jobs:
  tests:
    name: "Compile examples on py${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.8"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        id: setup_python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: vplanet
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}

      - name: Install
        id: install
        if: steps.setup_python.outcome == 'success'
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install -e .

      - name: Run tests
        if: steps.install.outcome == 'success'
        shell: bash -l {0}
        run: python docs/run_examples.py
